### PR TITLE
Fixed found bugs

### PR DESCRIPTION
**Pull request by kphanipavan**
- App UI Specifics:

Added null checks for disconnected case
Added new status "Scanning" and a yellow dot for it
App shows IP address beside Username
Changed to TextButton from FlatButton
Simplified Disconnected screens

- App Specifics:

App migrated to Android Embedding V2 thing
Migrated Splash Screen to V2 
Added Flutter 2.10 support
Added null safety

- Scripts:

Fixed method usage in data.py
Linux-dae-mon.py now uses data.py
Changed random sleep in daemon script to 1 second

### CODE REVIEW

**Comment by therexone** [comment]
:rocket: Can you attach a screenshot of the changed screens ?

**Comment by kphanipavan** [comment]
HomePage/Dashboard with IP address:

Screenshot_20220215_202631

Battery page working, added proper null checks:

Screenshot_20220215_202727

All the pages other than Dashboard show this "Disconnected" message instead of empty graphs:

Screenshot_20220215_202849

New Scanning state with yellow light when searching for servers:

Screenshot_20220215_203024

When a server is not found, the app used not to show this "No Server Found" DiagBox at the start, now it does:

Screenshot_20220215_203253

Known Bugs:
- When the server is disconnected after a successful connection, the state fluctuates between Connected and Disconnected. Scanning is not shown
- When the "No Server Found" DiagBox is dismissed instead of selecting rescan, the app just sits at the disconnected screen and doesn't rescan for servers. (lib/linux_mon.dart: 170  showDialog.barrierDismissible should be added and be set as false)

Comment if bugs found ples, will fix on sunday

Edit: fixed barrierDis thing with commit [7fcaa92](https://github.com/therexone/linux-mon/pull/4/commits/7fcaa92133070d036524d9ce8dea121ae7575f4d)

**Comment by therexone** [comment]
Please remove commented code for brevity.

**Review by therexone — APPROVED** [review]
🚀 LGTM

**Comment by kphanipavan** [comment]
> Please remove commented code for brevity.

Done this with commit [b85ada0](https://github.com/therexone/linux-mon/pull/4/commits/b85ada012a7dded3217d370ccb4b30aecd0918b8)

I also added a github actions file which builds an android apk to see if it actually build and discards it.

**Pull request merged**
